# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
# SPDX-FileCopyrightText: 2026 Manoel Gerlach <mail@manoel.us>
#
# SPDX-License-Identifier: Apache-2.0

blank_issues_enabled: false
contact_links:
  - name: Original project discussions
    url: https://github.com/royshil/obs-backgroundremoval/discussions
    about: Ask general questions about the original upstream project.
