# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
# SPDX-FileCopyrightText: 2026 Manoel Gerlach <mail@manoel.us>
#
# SPDX-License-Identifier: Apache-2.0

name: PR Check

on:
  pull_request:

permissions: {}

concurrency:
  group: pr-check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-windows-x64:
    uses: ./.github/workflows/build-windows.yml
    permissions:
      contents: read
    with:
      upload-artifacts: true
      attest-artifacts: false
      runs-on: windows-2025-vs2026
