# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
# SPDX-FileCopyrightText: 2026 Manoel Gerlach <mail@manoel.us>
#
# SPDX-License-Identifier: Apache-2.0

name: Push (main) CI

on:
  push:
    branches: [main]
  workflow_call:
    outputs:
      WINDOWS_X64_DLL_ARTIFACT:
        value: ${{ jobs.build-windows-x64.outputs.dll-artifact }}

permissions: {}

jobs:
  build-windows-x64:
    uses: ./.github/workflows/build-windows.yml
    permissions:
      artifact-metadata: write
      attestations: write
      contents: read
      id-token: write
    with:
      upload-artifacts: true
      attest-artifacts: true
      runs-on: windows-2025-vs2026
